version: '3.7'

services:

  app:
    container_name: via_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3200:3000
    environment:
      - CHOKIDAR_USEPOLLING=true