version: '3.7'

services:
  via_dev:
    container_name: via_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3200:3200
    environment:
      - CHOKIDAR_USEPOLLING=true